
---
apiVersion: v1
kind: Namespace
metadata:
  name: retail-store
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: retail-store
  name: retail-store
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: retail-store
  template:
    metadata:
      labels:
        app.kubernetes.io/name: retail-store
    spec:
      containers:
        - image: public.ecr.aws/aws-containers/retail-store-sample-ui:0.8.3
          name: retail-store
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  namespace: retail-store
  name: retail-store
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: retail-store
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: retail-store
  name: retail-store
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: retail-store
                port:
                  name: http
